package com.eleme.soa.ers;

public enum ERSErrorCode {
  UNKNOWN_ERROR(0), ACTIVITY_NOT_FOUND(1), ANONYMOUS_USER_PERMISSION_DENIED(2), APP_URL_NOT_FOUND(
      3), AREA_NOT_FOUND(4), BANKCARD_NOT_FOUND(5), BANKCARD_NOT_MATCH_CORPORATION(
          6), BANKCARD_WITH_NO_SUBSIDY(7), CITY_NOT_FOUND(8), COMMENT_NOT_FOUND(
              9), COMMENT_REPLY_NOT_FOUND(10), COUPON_ALREADY_USED(11), COUPON_NOT_FOUND(
                  12), COUPON_OUT_OF_DATE(13), DEVICE_RESTAURANT_NOT_FOUND(14), DIRECTOR_NOT_FOUND(
                      15), DISTRICT_NOT_FOUND(16), DOCK_CORP_NOT_FOUND(
                          17), DOCK_CORP_RESTAURANT_NOT_FOUND(18), DUPLICATED_DEVICE_RESTAURANT(
                              19), ENTRY_NOT_FOUND(20), ENTRY_RESTAURANT_NOT_FOUND(
                                  21), FOOD_ALREADY_HAS_FOOD_ACTIVITY(22), FOOD_ACTIVITY_NOT_FOUND(
                                      23), FOOD_ACTIVITY_CANT_CHANGE_CITY(
                                          24), FOOD_ACTIVITY_CANT_CHANGE_DISCOUNT(
                                              25), FOOD_ACTIVITY_HAS_NO_LIMIT(
                                                  26), FOOD_ACTIVITY_SUBSIDY_CANT_PROCESS(
                                                      27), FOOD_ACTIVITY_SUBSIDY_NOT_FOUND(
                                                          28), FOOD_ACTIVITY_FIELD_INVALID(
                                                              29), FOOD_ACTIVITY_EFFECT_INVALID(
                                                                  30), FOOD_CATEGORY_POSITION_INVALID(
                                                                      31), FOOD_CATEGORY_NOT_COMPLETE(
                                                                          32), FOOD_GROUP_RESTAURANT_DIVERSED(
                                                                              33), FOOD_NOT_FOUND(
                                                                                  34), FOOD_HAS_NO_CATEGORY_ID(
                                                                                      35), FOOD_NAME_CANNOT_CHANGE(
                                                                                          36), FOOD_PRICE_CHANGED_TOO_OFTEN(
                                                                                              37), FOOD_PRICE_CHANGED_TOO_MUCH(
                                                                                                  38), FOOD_CATEGORY_NOT_FOUND(
                                                                                                      39), FOOD_CATEGORY_NOT_BELONGS_TO_RESTAURANT(
                                                                                                          40), FOOD_REQUIRED_GARNISH_CONFLICT(
                                                                                                              41), FOOD_UGC_IMAGE_LIKE_TOO_FREQUENTLY(
                                                                                                                  42), FOOD_UGC_IMAGE_NOT_FOUND(
                                                                                                                      43), FOOD_UGC_IMAGE_PR_NOT_FOUND(
                                                                                                                          44), FOOD_POSITION_INVALID(
                                                                                                                              45), FOOD_NOT_COMPLETE(
                                                                                                                                  46), FRIEND_LINK_NOT_FOUND(
                                                                                                                                      47), GARNISH_NOT_FOUND(
                                                                                                                                          48), GARNISH_CATEGORY_NOT_FOUND(
                                                                                                                                              49), GEOHASH_NAME_NOT_FOUND(
                                                                                                                                                  50), GEOHASH_RESTAURANT_NOT_FOUND(
                                                                                                                                                      51), INVALID_DATE_RANGE(
                                                                                                                                                          52), INVALID_ENTRY(
                                                                                                                                                              53), INVALID_RESTAURANT(
                                                                                                                                                                  54), INVALID_RESTAURANT_AREA(
                                                                                                                                                                      55), INVALID_SUBSIDY(
                                                                                                                                                                          56), INVALID_TIME_RANGE(
                                                                                                                                                                              57), LOGO_NOT_FOUND(
                                                                                                                                                                                  58), MISSING_DEVICE_RESTAURANT_ATTRIBUTE(
                                                                                                                                                                                      59), MODE_ELEME_INVALID_OPEN_TIME(
                                                                                                                                                                                          60), PERMISSION_DENIED(
                                                                                                                                                                                              61), QUICK_MESSAGE_NOT_FOUND(
                                                                                                                                                                                                  62), REGION_AREA_TOO_LARGE(
                                                                                                                                                                                                      63), REGION_NOT_FOUND(
                                                                                                                                                                                                          64), REGION_GROUP_NOT_FOUND(
                                                                                                                                                                                                              65), RESTAURANT_ADMIN_NOT_FOUND(
                                                                                                                                                                                                                  66), RESTAURANT_AREA_TOO_LARGE(
                                                                                                                                                                                                                      67), RESTAURANT_CHANGE_RECORD_NOT_FOUND(
                                                                                                                                                                                                                          68), RESTAURANT_EVALUATION_NOT_FOUND(
                                                                                                                                                                                                                              69), RESTAURANT_HAS_NO_ACTIVITY_SUBSIDY(
                                                                                                                                                                                                                                  70), RESTAURANT_MESSAGE_NOT_FOUND(
                                                                                                                                                                                                                                      71), RESTAURANT_NOT_FOUND(
                                                                                                                                                                                                                                          72), RESTAURANT_OPEN_APPLY_NOT_FOUND(
                                                                                                                                                                                                                                              73), RESTAURANT_RATE_NOT_FOUND(
                                                                                                                                                                                                                                                  74), RESTAURANT_OPEN_APPLY_STATUS_INVALID(
                                                                                                                                                                                                                                                      75), RESTAURANT_PROMOTION_NOT_FOUND(
                                                                                                                                                                                                                                                          76), SAAS_CHANGE_RECORD_NOT_FOUND(
                                                                                                                                                                                                                                                              77), SAAS_CONTRACT_RECORD_NOT_FOUND(
                                                                                                                                                                                                                                                                  78), SAAS_CONTRACT_PLAN_TYPE_ERROR(
                                                                                                                                                                                                                                                                      79), SAAS_CONTRACT_RANKING_INFO_MISSING(
                                                                                                                                                                                                                                                                          80), SAAS_CONTRACT_RANKING_INFO_ALREADY_SET(
                                                                                                                                                                                                                                                                              81), SAAS_CONTRACT_RECORD_STATUS_ERROR(
                                                                                                                                                                                                                                                                                  82), SAAS_STATUS_ERROR(
                                                                                                                                                                                                                                                                                      83), SAAS_STATUS_NOT_FOUND(
                                                                                                                                                                                                                                                                                          84), SAAS_PAY_CANT_TO_FREE(
                                                                                                                                                                                                                                                                                              85), SAAS_TRIAL_DAYS_OVER_LIMIT(
                                                                                                                                                                                                                                                                                                  86), SAAS_SUSPENDED_RESTAURANT_CLOSED_ONLY(
                                                                                                                                                                                                                                                                                                      87), SAAS_CONTRACT_PLAN_NOT_FOUND(
                                                                                                                                                                                                                                                                                                          88), SAAS_CONTRACT_UPGRADE_OVERDUE(
                                                                                                                                                                                                                                                                                                              89), SAAS_CONTRACT_RELEVANT_RECORD_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                  90), SAAS_CONTRACT_RELEVANT_RECORD_ALREADY_UPGRADED(
                                                                                                                                                                                                                                                                                                                      91), SAAS_CONTRACT_RELEVANT_RECORD_NOT_NORMAL(
                                                                                                                                                                                                                                                                                                                          92), SAAS_CONTRACT_UPGRADE_PLAN_ERROR(
                                                                                                                                                                                                                                                                                                                              93), SAAS_CONTRACT_UPGRADE_RESTAURANT_ERROR(
                                                                                                                                                                                                                                                                                                                                  94), SAAS_CONTRACT_RECORD_ABANDONED(
                                                                                                                                                                                                                                                                                                                                      95), SAAS_CONTRACT_ONLY_ONE_NEW(
                                                                                                                                                                                                                                                                                                                                          96), SAAS_CONTRACT_COMBO_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                              97), SAAS_CONTRACT_COMBO_ONE_FOR_RESTAURNT(
                                                                                                                                                                                                                                                                                                                                                  98), SAAS_CONTRACT_COMBO_NOT_PAYABLE(
                                                                                                                                                                                                                                                                                                                                                      99), SAAS_CONTRACT_COMBO_USER_LACK_OF_BALANCE(
                                                                                                                                                                                                                                                                                                                                                          100), SAAS_CONTRACT_COMBO_CONFIRM_OVERLOAD(
                                                                                                                                                                                                                                                                                                                                                              101), SEO_SM_INDEX_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                  102), STOCK_NOT_ENOUGH(
                                                                                                                                                                                                                                                                                                                                                                      103), TOO_MANY_FOOD_UGC_IMAGES(
                                                                                                                                                                                                                                                                                                                                                                          104), USER_AUTH_FAIL(
                                                                                                                                                                                                                                                                                                                                                                              105), CL_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                  106), DL_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                      107), AREA_OUT_OF_CITY(
                                                                                                                                                                                                                                                                                                                                                                                          108), ZONE_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                              109), INVALID_NAME_FOR_URL(
                                                                                                                                                                                                                                                                                                                                                                                                  110), FOOD_CATEGORY_ONE_ATRR_ONLY(
                                                                                                                                                                                                                                                                                                                                                                                                      111), ONLINE_PAYMENT_APPLY_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                          112), ONLINE_PAYMENT_APPLY_ALREADY_PROCESSED(
                                                                                                                                                                                                                                                                                                                                                                                                              113), DELIVER_AREA_MUST_IN_UPDATE(
                                                                                                                                                                                                                                                                                                                                                                                                                  114), INVALID_RESTAURANT_DELIVER_PRICE(
                                                                                                                                                                                                                                                                                                                                                                                                                      115), INVALID_MOBILE(
                                                                                                                                                                                                                                                                                                                                                                                                                          116), DUPLICATED_FOOD_UGC_IMAGE(
                                                                                                                                                                                                                                                                                                                                                                                                                              117), APP_CAMPAIGN_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                  118), TOO_MANY_POLYGON_IN_DELIVER_AREA(
                                                                                                                                                                                                                                                                                                                                                                                                                                      119), DUPLICATED_POLYGON_IN_DELIVER_AREA(
                                                                                                                                                                                                                                                                                                                                                                                                                                          120), ORDER_IN_PENDING(
                                                                                                                                                                                                                                                                                                                                                                                                                                              121), TOO_MANY_POLYGON_IN_DELIVER_GEOJSON(
                                                                                                                                                                                                                                                                                                                                                                                                                                                  122), RESTAURANT_POLYGON_AREA_TOO_LARGE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                      123), INVALID_RESTAURANT_GEOMETRY(
                                                                                                                                                                                                                                                                                                                                                                                                                                                          124), MISS_PROPERTY_IN_DELIVER_GEOJSON(
                                                                                                                                                                                                                                                                                                                                                                                                                                                              125), DUPLICATED_POLYGON_IN_DELIVER_GEOJSON(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  126), RESTAURANT_COMMENT_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      127), INVALID_STOCK(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          128), FOOD_GARNISH_CATEGORY_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              129), ACTIVITY_ICON_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  130), FREE_GIFT_ACTIVITY_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      131), ORDER_MODE_CORP_TYPE_NOT_MATCH(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          132), RESTAURANT_ACTIVITY_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              133), RESTAURANT_ACTIVITY_FIELD_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  134), CERTIFICATION_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      135), CERTIFICATION_HAS_EXISTED(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          136), CERTIFICATION_UPDATE_DENIED(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              137), CERTIFICATION_PROCESS_ILLEGAL(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  138), INVALID_REGION_AREA(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      139), INVALID_RESTAURANT_ATTRIBUTE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          140), DELIVERY_PRICE_MUST_BE_FIGURE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              141), INVALUD_FOOD_DISCOUNT(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  142), ACTIVITY_CONTRACT_NOT_SIGNED(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      143), AMENDED_POI_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          144), RESTAURANT_HAS_TOO_MANY_FOODS(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              145), VALIDATION_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  146), VALIDATION_NONEXIST_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      147), EOS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          148), EUS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              149), GEOS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  150), EES_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      151), DMS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          152), SMS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              153), OAS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  154), TDS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      155), DATABASE_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          156), INVALID_FIELD_VALUE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              157), INVALID_OPEN_TIME(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  158), TOO_BUSY_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      159), EPS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          160), ERS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              161), RESTAURANT_DIST_SWITCH_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  162), NON_SD_CANNOT_UPDATE_METHOD_OF_PAYMENT_DIRECTLY(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      163), DELIVERY_PRICE_TOO_LARGE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          164), RESTAURANT_NEWFLAVOR_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              165), FOOD_GARNISH_RELATION_ALREADY_EXIST(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  166), FOOD_GARNISH_RELATION_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      167), SUBSIDY_CONTRACT_ALREADY_APPROVED(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          168), RESTAURANT_BUSINESS_REGISTRATION_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              169), INVALID_KEEPER(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  170), RESTAURANT_ALREADY_HAVE_ADMIN(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      171), USER_ALREADY_RESTAURANT_ADMIN(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          172), USER_CERTIFICATION_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              173), USER_CERTIFICATION_DUPLICATE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  174), USER_CERTIFICATION_APPLY_TYPE_NOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      175), USER_CERTIFICATION_APPLY_TYPE_INVALID(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          176), USER_CERTIFICATION_APPLY_PASS_EDIT(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              177), ONLINE_PAYMENT_RESTAURANT_MUST_HAVE_ADMIN(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  178), GEOHASH_NOT_VALID(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      179), INVALID_FEE_VALUE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          180), FOOD_INVALID(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              181), AGENT_FEE_MUST_BE_FIGURE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  182), RESTAURANT_BRAND_RANK_CANNOT_FOUND(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      183), RESTAURANT_CANNOT_UPDATE_BUSY_LEVEL(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          184), CERTIFICATION_LICENSE_INVALID(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              185), RESTAURANT_AGENT_FEE_CANNOT_EDIT(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  186), RESTAURANT_AGENT_FEE_TOO_LARGE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      187), API_NOT_AVAILABLE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          188), TEST_RESTAURANT_MUST_HAS_TEST_TYPE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              189), EWS_CLIENT_ERROR(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  190), FOOD_RESTAURANT_CAN_NOT_CHANGE(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      191), FOOD_NAME_CAN_NOT_BE_EMPTY(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          192);

  private final int value;

  private ERSErrorCode(int value) {
    this.value = value;
  }

  /**
   * convert to int
   */
  public int getValue() {
    return value;
  }

  /**
   * convert from int
   */
  public static ERSErrorCode get(int value) {
    for (ERSErrorCode e : values()) {
      if (e.getValue() == value) {
        return e;
      }
    }
    return null;
  }
}
